name: VK_Workflow-1


on:
  workflow_dispatch:
  
jobs:
 
  build:
   
    runs-on: ubuntu-latest

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: vikashkumar707/VK-2
          event-type: my-event
